openapi: 3.0.3
info:
  title: Delivery Microservice
  description: APIs for delivering orders
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Order
  - name: Courier
  - name: Vendor
  - name: Analytics

paths:
  /courier/delivery/{courier_id}/available-orders:
    get:
      summary: Get all available orders
      tags:
        - Courier
      parameters:
        - name: courier_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 10
          description: Unique identifier of the courier
        - name: authorizationId
          in: header
          required: true
          schema:
            type: integer
            example: 1
          description: Identification of the user who is making the request
      responses:
        '200':
          description: A list of available order IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
                  description: Unique identifier of an order
              examples:
                availableOrders:
                  summary: Example of available order IDs
                  value: [ 101, 102, 103 ]
        '400':
          description: Bad request if the courier ID is not valid
        '403':
          description: Forbidden access
        '404':
          description: Courier not found

  /courier/delivery/{courier_id}/orders:
    get:
      summary: Get orders assigned to a courier
      tags:
        - Courier
      description: Retrieve a set of order IDs that are currently assigned to a courier.
      parameters:
        - name: courier_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
          description: Unique identifier of the courier
        - name: authorizationId
          in: header
          required: true
          schema:
            type: integer
            example: 20
          description: Identification of the user who is making the request
      responses:
        '200':
          description: A list of assigned order IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
                  description: Unique identifier of an order
              examples:
                assignedOrders:
                  summary: Example of assigned order IDs
                  value: [ 201, 202, 203 ]
        '400':
          description: Bad request if the courier ID is not valid
        '403':
          description: Forbidden access
        '404':
          description: Resources could not be found

  /courier/delivery/{courier_id}/assign/{order_id}:
    put:
      summary: Assign a specific order to a courier
      tags:
        - Courier
      description: Assign an order to a courier by specifying the order ID in the path.
      parameters:
        - name: courier_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 10
          description: Unique identifier of the courier
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
          description: Unique identifier of the order to assign
        - name: authorizationId
          in: header
          required: true
          schema:
            type: integer
            example: 1
          description: Identification of the user who is making the request
      responses:
        '200':
          description: Order successfully assigned to the courier
        '400':
          description: Bad request if the courier ID or order ID is not valid
        '403':
          description: Forbidden access
        '404':
          description: Some resources were not found

  /courier/delivery/{courier_id}/assign-any-order:
    put:
      summary: Assign any available order to a courier
      tags:
        - Courier
      description: Automatically assigns an available order to the courier.
      parameters:
        - name: courier_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 10
          description: Unique identifier of the courier
        - name: authorizationId
          in: header
          required: true
          schema:
            type: integer
            example: 1
          description: Identification of the user who is making the request
      responses:
        '200':
          description: An available order has been successfully assigned to the courier.
        '400':
          description: Bad request if the courier ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Some resources could not be found

  /delivery:
    parameters:
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    post:
      summary: Create a delivery
      tags:
        - Order
      description: Given the information of a Delivery, an object is created and persisted in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: integer
                  description: Unique identifier for the order
                  example: 12
                customer_id:
                  type: integer
                  description: Unique identifier for the customer
                  example: 45
                destination:
                  type: object
                  description: Location of the customer
                  example:
                    longitude: 12.33239039
                    latitude: 104.238381
                vendor_id:
                  type: integer
                  description: Unique identifier of the vendor
                  example: 4
              required:
                - customer_id
                - order_id
                - destination
                - vendor_id
      responses:
        '200':
          description: Successful Request
        '400':
          description: There was a problem with the request
        '403':
          description: Forbidden access

  /delivery/order/{order_id}/status:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Order status
      tags:
        - Order
      description: Get the status of the order (i.e. Delivered, In Transit, ...)
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: string
                example: "Preparing"
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
    put:
      summary: Change order status
      tags:
        - Order
      description: Change the status of the order (Preparing -> In Transit)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              example: "Preparing"
      responses:
        '200':
          description: Successful Request
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
  /delivery/order/{order_id}/eta:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Order ETA
      tags:
        - Order
      description: Get the estimated time of arrival of an order
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2023-07-16T19:20:30
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
    put:
      summary: Change order ETA
      tags:
        - Order
      description: Change the estimated time of arrival for an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: date-time
              example: 2025-07-16T19:20:30+01:00
      responses:
        '200':
          description: Successful Request
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
  /delivery/order/{order_id}/ready-time:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Get the estimated ready time
      tags:
        - Order
      description: Get the estimated ready time
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2023-07-16T19:20:30
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
    put:
      summary: Change order ready-time
      tags:
        - Order
      description: Change the estimated time of when order will be ready for delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: date-time
              example: 2025-07-16T19:20:30+01:00
      responses:
        '200':
          description: Successful Request
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '500':
          description: There was a problem with the server
  /delivery/order/{order_id}/tod:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Get the time of delivery of an order
      tags:
        - Order
      description: Get the time of delivery of an order
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2023-07-16T19:51:34
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server
    put:
      summary: Put order Time of Delivery
      tags:
        - Order
      description: Input the order delivery time
      requestBody:
        required: true
        description: Delivered time
        content:
          application/json:
            schema:
              type: string
              format: date-time
              example: 2025-07-16T19:20:30+01:00
      responses:
        '200':
          description: successful
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
  /delivery/order/{order_id}/pickup-time:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Order pickup time
      tags:
        - Order
      description: Get the pickup time of the order
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2023-07-16T19:51:34
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
    put:
      summary:  Put order pickup time
      tags:
        - Order
      description: Input the order pickup time
      requestBody:
        description: Pickup time
        required: true
        content:
          application/json:
            schema:
              type: string
              format: date-time
              example: 2023-07-16T19:51:34
      responses:
        '200':
          description: successful
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server
  /delivery/order/{order_id}/courier:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Order courier id
      tags:
        - Order
      description: Get the courier id that is assigned to an order
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                type: integer
                example: 74
        '204':
          description: No courier assigned to this order
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server

  /delivery/order/{order_id}/issue:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: Unique identifier of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    put:
      summary: Issue occurred in delivery process
      tags:
        - Order
      description: We input an issue related to a delivery
      requestBody:
        description: Issue details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'

      responses:
        '200':
          description: successful
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server

    get:
      summary: Retrieve issue that occurred during delivery process
      tags:
        - Order
      description: Given order returns the issue that occurred during delivery process
      responses:
        '200':
          description: returns issue details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server

  /analytics/courier/{courier_id}/efficiency:
    parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          example: "3"
        description: The id of the courier
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Get the efficiency of a courier
      tags:
        - Analytics
      description: Calculate the efficiency of the deliveries a courier has made
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: integer
                example: "70"
        '400':
          description: Bad request if the courier ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Courier not found
        '500':
          description: There was a problem with the server
  /analytics/courier/{courier_id}/deliveries-per-day:
    parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          example: "75"
        description: The id of the courier
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Deliveries/day of a courier
      tags:
        - Analytics
      description: Retrieve the average number of deliveries a courier has made/day
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: integer
                example: "3"
        '400':
          description: Bad request if the courier ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Courier not found
        '500':
          description: There was a problem with the server
  /analytics/courier/{courier_id}/successful-deliveries:
    parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          example: "3"
        description: The id of the courier
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Number of successful deliveries of a courier
      tags:
        - Analytics
      description: Retrieve the number of successful deliveries a courier has made
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: integer
                example: "53"
        '400':
          description: Bad request if the courier ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Courier not found
        '500':
          description: There was a problem with the server
  /analytics/courier/{courier_id}/courier-issues:
    parameters:
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          example: "3"
        description: The id of the courier
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Issues of a courier
      tags:
        - Analytics
      description: Retrieve the issues a courier has encountered during deliveries
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: "traffic, accident"
        '400':
          description: Bad request if the courier ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Courier not found
        '500':
          description: There was a problem with the server
  /analytics/vendor/{vendor_id}/vendor-average:
    parameters:
      - name: vendor_id
        in: path
        required: true
        schema:
          type: integer
          example: "3"
        description: The id of the vendor
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Average delivery times for a vendor
      tags:
        - Analytics
      description: Retrieve the average delivery times for a vendor
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: integer
                example: "2"
        '400':
          description: Bad request if the vendor ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Vendor not found
        '500':
          description: There was a problem with the server

  /analytics/order/{order_id}/rating:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: "3"
        description: The id of the order
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    put:
      summary: Set the rating of an order
      tags:
        - Analytics
      description: Set the rating of an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rating'
      responses:
        '200':
          description: successful
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server
    get:
      summary: Rating for an order
      tags:
        - Analytics
      description: Retrieve the rating for an order
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server
  /delivery/order/{order_id}/location:
    parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          example: 7
        description: The unique identifier of the order.
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    put:
      summary: Update Order Location
      tags:
        - Order
      description: |
        Sets the current location of the courier carrying the delivery for the order with ID order_id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: Courier location updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
              example:
                latitude: 37.7749
                longitude: -122.4194
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request
    get:
      summary: Current location of an order
      tags:
        - Order
      description: Retrieve the current location for an order
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '400':
          description: Bad request if the order ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order not found
        '500':
          description: There was a problem with the server

  /vendor/delivery/{vendor_id}/assign/{courier_id}:
    parameters:
      - name: vendor_id
        in: path
        required: true
        schema:
          type: integer
          example: 8
        description: The unique identifier of the order.
      - name: courier_id
        in: path
        required: true
        schema:
          type: integer
          example: 10
        description: The unique identifier of the courier.
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 30
        description: Identification of the user who is making the request
    put:
      summary: Assign Courier to Vendor
      tags:
        - Vendor
      description: |
        Assigns the courier with ID courier_id to the vendor with ID vendor_id.
      responses:
        '200':
          description: Vendor updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
              example:
                id: 123
                customer:
                  id: 456
                  # ... other customer properties
                vendor:
                  id: 789
                  # ... other vendor properties
                status: "asc"
                destination:
                  latitude: 37.7749
                  longitude: -122.4194
                # ... other order properties
                courier:
                  currentLocation:
                    latitude: 37.7896
                    longitude: -122.3906
                  activeDelivery:
                    id: 987
                    # ... other delivery properties
                # ... other courier properties
        '400':
          description: Bad request if the order ID or courier ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Order or Courier not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request
  /vendor/delivery/{vendor_id}/couriers:
    parameters:
      - name: vendor_id
        in: path
        required: true
        schema:
          type: integer
          example: 20
        description: The unique identifier of the vendor.
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 1
        description: Identification of the user who is making the request
    get:
      summary: Retrieve Couriers Assigned to Vendor
      tags:
        - Vendor
      description: |
        Retrieves all couriers assigned to the vendor with the specified ID.
      responses:
        '200':
          description: Couriers retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
                  description: ids of couriers
              example:
                - 5
                - 7
                - 9
        '400':
          description: Bad request if the Vendor ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Vendor not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request

  /delivery/default-delivery-zone:
    parameters:
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 20
        description: Identification of the user who is making the request
    get:
      summary: Retrieve the default delivery zone set by the admin
      tags:
        - Order
      description: |
        Retrieve the default delivery zone radius set by the admin.
      responses:
        '200':
          description: Delivery zone retrieved successfully.
          content:
            application/json:
              schema:
                type: integer
              example: 5
        '403':
          description: Forbidden access
        '404':
          description: Value not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request
    put:
      summary: Update the default Delivery Zone
      tags:
        - Order
      description: |
        Sets the default delivery zone radius.
      requestBody:
        description: Default delivery zone radius
        required: true
        content:
          application/json:
            schema:
              type: integer
              example: 8
      responses:
        '200':
          description: Delivery zone updated successfully.
        '403':
          description: Forbidden access
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request

  /vendor/delivery/{vendor_id}/delivery-zone:
    parameters:
      - name: vendor_id
        in: path
        required: true
        schema:
          type: integer
          example: 20
        description: The unique identifier of the vendor.
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 20
        description: Identification of the user who is making the request
    get:
      summary: Retrieve Vendor Delivery Zone
      tags:
        - Vendor
      description: |
        Retrieves the delivery zone, which is a radius of the vendor with the specified ID.
      responses:
        '200':
          description: Delivery zone retrieved successfully.
          content:
            application/json:
              schema:
                type: integer
              example: 5
        '400':
          description: Bad request if the Vendor ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Vendor not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request


    put:
      summary: Update Vendor Delivery Zone
      tags:
        - Vendor
      description: |
        Sets the delivery zone radius of the vendor with the specified ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: radius of the delivery zone
              example: 7
      responses:
        '200':
          description: Delivery zone updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
              example:
                id: 123
                deliveryZone: 7
                address:
                  latitude: 37.7749
                  longitude: -122.4194
                couriers:
                  - currentLocation:
                      latitude: 37.7749
                      longitude: -122.4194
                    activeDelivery: null
        '400':
          description: Bad request if the Vendor ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Vendor not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred while processing the request



  /vendor/delivery/{vendor_id}/vendor-address:
    parameters:
      - name: vendor_id
        in: path
        required: true
        schema:
          type: integer
          example: 20
        description: Unique identifier of the vendor.
      - name: authorizationId
        in: header
        required: true
        schema:
          type: integer
          example: 3
        description: Identification of the user who is making the request
    get:
      summary: Retrieve Vendor Address
      tags:
        - Vendor
      description: |
        Retrieves the address of the specified vendor identified by `vendor_id`.
      responses:
        '200':
          description: Vendor Address Retrieved Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
              example:
                latitude: 37.7749
                longitude: -122.4194
        '400':
          description: Bad request if the Vendor ID is invalid
        '403':
          description: Forbidden access
        '404':
          description: Vendor not found


components:
  schemas:
    Order:
      type: object
      properties:
        orderId:
          type: integer
          format: int64
          description: Identifier for the order of the delivery
          example: "3"
          x-field-extra-annotation: "@javax.persistence.Id"
        customerId:
          type: integer
          format: int64
        vendor:
          $ref: '#/components/schemas/Vendor'
        status:
          type: string
          enum:
            - Pending
            - Accepted
            - Rejected
            - Preparing
            - Given_To_Courier
            - On_Transit
            - Delivered
          example: "Preparing"
        destination:
          $ref: '#/components/schemas/Location'
      x-class-extra-annotation: "@javax.persistence.Entity @javax.persistence.Table(name = \"orders\") @lombok.Builder @lombok.AllArgsConstructor @lombok.NoArgsConstructor"
      x-field-extra-annotation: "@javax.persistence.OneToOne(cascade = javax.persistence.CascadeType.ALL)"
    Delivery:
      type: object
      properties:
        id:
          type: integer
          format: uuid
          description: Unique identifier for the delivery
          example: "3"
          x-field-extra-annotation: "@javax.persistence.Id"
        order:
          $ref: '#/components/schemas/Order'
        courier_id:
          type: integer
          description: the id of the Courier assigned to the delivery
        rating:
          $ref: '#/components/schemas/Rating'
        time:
          $ref: '#/components/schemas/Time'
        issue:
          $ref: '#/components/schemas/Issue'
      x-class-extra-annotation: "@javax.persistence.Entity @javax.persistence.Table(name = \"deliveries\") @lombok.Builder @lombok.AllArgsConstructor @lombok.NoArgsConstructor"
    Vendor:
      type: object
      x-field-extra-annotation: "@javax.persistence.ManyToOne(cascade = javax.persistence.CascadeType.ALL)"
      properties:
        id:
          type: integer
          format: int64
          description: The id of the User
          example: "3"
          x-field-extra-annotation: "@javax.persistence.Id"
        deliveryZone:
          type: integer
          format: int64
          description: The radius of the delivery zone of the Vendor
          example: "50"
        address:
          $ref: '#/components/schemas/Location'
        couriers:
          type: array
          items:
            type: integer
            format: int64
            description: the list of courier ids
          x-field-extra-annotation: "@javax.persistence.ElementCollection"
      x-class-extra-annotation: "@javax.persistence.Entity @javax.persistence.Table(name = \"vendors\") @lombok.Builder @lombok.AllArgsConstructor @lombok.NoArgsConstructor"

    Location:
      type: object
      x-field-extra-annotation: "@javax.persistence.Embedded"
      x-class-extra-annotation: "@javax.persistence.Embeddable @lombok.AllArgsConstructor @lombok.NoArgsConstructor"
      properties:
        latitude:
          type: number
          format: double
          description: The latitude of the location
          example: 12.33239039
        longitude:
          type: number
          format: double
          description: The longitude of the location
          example: 104.238381
    Time:
      type: object
      x-field-extra-annotation: "@javax.persistence.Embedded"
      x-class-extra-annotation: "@javax.persistence.Embeddable @lombok.Builder @lombok.AllArgsConstructor @lombok.NoArgsConstructor"
      properties:
        pickUpTime:
          type: string
          format: date-time
          example: 2023-07-16T19:51:34
          description: The time when an order was picked up
        readyTime:
          type: string
          format: date-time
          example: 2023-07-16T19:51:34
          description: The estimation time for when an order will be ready
        deliveredTime:
          type: string
          format: date-time
          example: 2023-07-16T19:51:34
          description: The time when an order was delivered
    Issue:
      type: object
      x-field-extra-annotation: "@javax.persistence.Embedded"
      x-class-extra-annotation: "@javax.persistence.Embeddable @lombok.AllArgsConstructor @lombok.NoArgsConstructor"
      properties:
        typeOfIssue:
          type: string
          example: "accident"
        description:
          type: string
          example: "I got into an accident while delivering"
    Rating:
      type: object
      x-field-extra-annotation: "@javax.persistence.Embedded"
      x-class-extra-annotation: "@javax.persistence.Embeddable @lombok.AllArgsConstructor @lombok.NoArgsConstructor"
      properties:
        grade:
          type: integer
          example: "3"
        comment:
          type: string
          description: "Very fast delivery"